
# This is a file for things related to the 27 JEC variations
#   - For things that would be too long and messy to keep in our regular scripts, but want to keep them around for reference

SYSTS_SPECIAL = {
    "UL16APV" : {
        "CMS_btag_fixedWP_incl_light_uncorrelated_2016APV"    : {"yr_rel":"UL16APV", "yr_notrel": []},
        "CMS_btag_fixedWP_comb_bc_uncorrelated_2016APV"       : {"yr_rel":"UL16APV", "yr_notrel": []},
        "Regrouped_Absolute_2016APV_uncorrelated"             : {"yr_rel":"UL16APV", "yr_notrel": []}, 
        "Regrouped_HF_2016APV_uncorrelated"                   : {"yr_rel":"UL16APV", "yr_notrel": []}, 
        "Regrouped_EC2_2016APV_uncorrelated"                  : {"yr_rel":"UL16APV", "yr_notrel": []}, 
        "Regrouped_RelativeSample_2016APV_uncorrelated"       : {"yr_rel":"UL16APV", "yr_notrel": []}, 
        "Regrouped_BBEC1_2016APV_uncorrelated"                : {"yr_rel":"UL16APV", "yr_notrel": []}, 
        "CMS_res_j_2016APV"                                   : {"yr_rel":"UL16APV", "yr_notrel": []},
        "CMS_scale_met_unclustered_energy_2016APV"            : {"yr_rel":"UL16APV", "yr_notrel": []},
    },
    "UL16" : {
        "CMS_btag_fixedWP_incl_light_uncorrelated_2016"    : {"yr_rel":"UL16", "yr_notrel": []},
        "CMS_btag_fixedWP_comb_bc_uncorrelated_2016"       : {"yr_rel":"UL16", "yr_notrel": []},
        "Regrouped_Absolute_2016_uncorrelated"             : {"yr_rel":"UL16", "yr_notrel": []}, 
        "Regrouped_HF_2016_uncorrelated"                   : {"yr_rel":"UL16", "yr_notrel": []}, 
        "Regrouped_EC2_2016_uncorrelated"                  : {"yr_rel":"UL16", "yr_notrel": []}, 
        "Regrouped_RelativeSample_2016_uncorrelated"       : {"yr_rel":"UL16", "yr_notrel": []}, 
        "Regrouped_BBEC1_2016_uncorrelated"                : {"yr_rel":"UL16", "yr_notrel": []}, 
        "CMS_res_j_2016"                                   : {"yr_rel":"UL16", "yr_notrel": []},
        "CMS_scale_met_unclustered_energy_2016"            : {"yr_rel":"UL16", "yr_notrel": []},
    },
    "UL17" : {
        "CMS_btag_fixedWP_incl_light_uncorrelated_2017"    : {"yr_rel":"UL17", "yr_notrel": []},
        "CMS_btag_fixedWP_comb_bc_uncorrelated_2017"       : {"yr_rel":"UL17", "yr_notrel": []},
        "Regrouped_Absolute_2017_uncorrelated"             : {"yr_rel":"UL17", "yr_notrel": []}, 
        "Regrouped_HF_2017_uncorrelated"                   : {"yr_rel":"UL17", "yr_notrel": []}, 
        "Regrouped_EC2_2017_uncorrelated"                  : {"yr_rel":"UL17", "yr_notrel": []}, 
        "Regrouped_RelativeSample_2017_uncorrelated"       : {"yr_rel":"UL17", "yr_notrel": []}, 
        "Regrouped_BBEC1_2017_uncorrelated"                : {"yr_rel":"UL17", "yr_notrel": []}, 
        "CMS_res_j_2017"                                   : {"yr_rel":"UL17", "yr_notrel": []},
        "CMS_scale_met_unclustered_energy_2017"            : {"yr_rel":"UL17", "yr_notrel": []},
    },
    "UL18" : {
        "CMS_btag_fixedWP_incl_light_uncorrelated_2018"    : {"yr_rel":"UL18", "yr_notrel": []},
        "CMS_btag_fixedWP_comb_bc_uncorrelated_2018"       : {"yr_rel":"UL18", "yr_notrel": []},
        "Regrouped_Absolute_2018_uncorrelated"             : {"yr_rel":"UL18", "yr_notrel": []}, 
        "Regrouped_HF_2018_uncorrelated"                   : {"yr_rel":"UL18", "yr_notrel": []}, 
        "Regrouped_EC2_2018_uncorrelated"                  : {"yr_rel":"UL18", "yr_notrel": []}, 
        "Regrouped_RelativeSample_2018_uncorrelated"       : {"yr_rel":"UL18", "yr_notrel": []}, 
        "Regrouped_BBEC1_2018_uncorrelated"                : {"yr_rel":"UL18", "yr_notrel": []}, 
        "CMS_res_j_2018"                                   : {"yr_rel":"UL18", "yr_notrel": []},
        "CMS_scale_met_unclustered_energy_2018"            : {"yr_rel":"UL18", "yr_notrel": []},
    },
    "run2" : {
        "CMS_btag_fixedWP_incl_light_uncorrelated_2016APV" : {"yr_rel":"UL16APV", "yr_notrel": ["UL16", "UL17", "UL18"]},
        "CMS_btag_fixedWP_comb_bc_uncorrelated_2016APV"    : {"yr_rel":"UL16APV", "yr_notrel": ["UL16", "UL17", "UL18"]},
        "CMS_res_j_2016APV"                                : {"yr_rel":"UL16APV", "yr_notrel": ["UL16", "UL17", "UL18"]},
        "CMS_scale_met_unclustered_energy_2016APV"         : {"yr_rel":"UL16APV", "yr_notrel": ["UL16", "UL17", "UL18"]},
        "Regrouped_Absolute_2018_uncorrelated"             : {"yr_rel":"UL16APV", "yr_notrel": ["UL16", "UL17", "UL18"]}, 
        "Regrouped_HF_2018_uncorrelated"                   : {"yr_rel":"UL16APV", "yr_notrel": ["UL16", "UL17", "UL18"]}, 
        "Regrouped_EC2_2018_uncorrelated"                  : {"yr_rel":"UL16APV", "yr_notrel": ["UL16", "UL17", "UL18"]}, 
        "Regrouped_RelativeSample_2018_uncorrelated"       : {"yr_rel":"UL16APV", "yr_notrel": ["UL16", "UL17", "UL18"]}, 
        "Regrouped_BBEC1_2018_uncorrelated"                : {"yr_rel":"UL16APV", "yr_notrel": ["UL16", "UL17", "UL18"]}, 

        "CMS_btag_fixedWP_incl_light_uncorrelated_2016"    : {"yr_rel":"UL16", "yr_notrel": ["UL16APV", "UL17", "UL18"]},
        "CMS_btag_fixedWP_comb_bc_uncorrelated_2016"       : {"yr_rel":"UL16", "yr_notrel": ["UL16APV", "UL17", "UL18"]},
        "CMS_res_j_2016"                                   : {"yr_rel":"UL16", "yr_notrel": ["UL16APV", "UL17", "UL18"]},
        "CMS_scale_met_unclustered_energy_2016"            : {"yr_rel":"UL16", "yr_notrel": ["UL16APV", "UL17", "UL18"]},
        "Regrouped_Absolute_2018_uncorrelated"             : {"yr_rel":"UL16", "yr_notrel": ["UL16APV", "UL17", "UL18"]}, 
        "Regrouped_HF_2018_uncorrelated"                   : {"yr_rel":"UL16", "yr_notrel": ["UL16APV", "UL17", "UL18"]}, 
        "Regrouped_EC2_2018_uncorrelated"                  : {"yr_rel":"UL16", "yr_notrel": ["UL16APV", "UL17", "UL18"]}, 
        "Regrouped_RelativeSample_2018_uncorrelated"       : {"yr_rel":"UL16", "yr_notrel": ["UL16APV", "UL17", "UL18"]}, 
        "Regrouped_BBEC1_2018_uncorrelated"                : {"yr_rel":"UL16", "yr_notrel": ["UL16APV", "UL17", "UL18"]}, 

        "CMS_btag_fixedWP_incl_light_uncorrelated_2017"    : {"yr_rel":"UL17", "yr_notrel": ["UL16APV", "UL16", "UL18"]},
        "CMS_btag_fixedWP_comb_bc_uncorrelated_2017"       : {"yr_rel":"UL17", "yr_notrel": ["UL16APV", "UL16", "UL18"]},
        "CMS_res_j_2017"                                   : {"yr_rel":"UL17", "yr_notrel": ["UL16APV", "UL16", "UL18"]},
        "CMS_scale_met_unclustered_energy_2017"            : {"yr_rel":"UL17", "yr_notrel": ["UL16APV", "UL16", "UL18"]},
        "Regrouped_Absolute_2018_uncorrelated"             : {"yr_rel":"UL17", "yr_notrel": ["UL16APV", "UL16", "UL18"]}, 
        "Regrouped_HF_2018_uncorrelated"                   : {"yr_rel":"UL17", "yr_notrel": ["UL16APV", "UL16", "UL18"]}, 
        "Regrouped_EC2_2018_uncorrelated"                  : {"yr_rel":"UL17", "yr_notrel": ["UL16APV", "UL16", "UL18"]}, 
        "Regrouped_RelativeSample_2018_uncorrelated"       : {"yr_rel":"UL17", "yr_notrel": ["UL16APV", "UL16", "UL18"]}, 
        "Regrouped_BBEC1_2018_uncorrelated"                : {"yr_rel":"UL17", "yr_notrel": ["UL16APV", "UL16", "UL18"]}, 

        "CMS_btag_fixedWP_incl_light_uncorrelated_2018"    : {"yr_rel":"UL18", "yr_notrel": ["UL16APV", "UL16", "UL17"]},
        "CMS_btag_fixedWP_comb_bc_uncorrelated_2018"       : {"yr_rel":"UL18", "yr_notrel": ["UL16APV", "UL16", "UL17"]},
        "CMS_res_j_2018"                                   : {"yr_rel":"UL18", "yr_notrel": ["UL16APV", "UL16", "UL17"]},
        "CMS_scale_met_unclustered_energy_2018"            : {"yr_rel":"UL18", "yr_notrel": ["UL16APV", "UL16", "UL17"]},
        "Regrouped_Absolute_2018_uncorrelated"             : {"yr_rel":"UL18", "yr_notrel": ["UL16APV", "UL16", "UL17"]}, 
        "Regrouped_HF_2018_uncorrelated"                   : {"yr_rel":"UL18", "yr_notrel": ["UL16APV", "UL16", "UL17"]}, 
        "Regrouped_EC2_2018_uncorrelated"                  : {"yr_rel":"UL18", "yr_notrel": ["UL16APV", "UL16", "UL17"]}, 
        "Regrouped_RelativeSample_2018_uncorrelated"       : {"yr_rel":"UL18", "yr_notrel": ["UL16APV", "UL16", "UL17"]}, 
        "Regrouped_BBEC1_2018_uncorrelated"                : {"yr_rel":"UL18", "yr_notrel": ["UL16APV", "UL16", "UL17"]}, 

    },

}
